###########################\u8FBE\u68A6DM\u9A71\u52A8\u914D\u7F6E#######################
#\u9ED8\u8BA4\u7248\u672C
jdbc.driver.default=V18
jdbc.driver.type=DM
#dm\u9A71\u52A8\u4E0B\u8F7D\u5730\u5740
jdbc.driver.download.url=https://repo.maven.apache.org/maven2/com/dameng/DmJdbcDriver18/8.1.2.192/DmJdbcDriver18-8.1.2.192.jar,https://github.com/wp2code/kaleido-repo/releases/download/v1/DmJdbcDriver18-8.1.2.192.jar
jdbc.driver.class=dm.jdbc.driver.DmDriver
jdbc.driver.version=V18
jdbc.driver.url=jdbc:dm://%s:%d
