spring:
  application:
    name: kaleido
  profiles:
    active: @environment@
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  messages:
    basename: i18n/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  jmx:
    enabled: false
  jackson:
    serialization:
      write-dates-as-timestamps: true
  freemarker:
    check-template-location: false
  #  用于数据库表结构版本管理
  flyway:
    enabled: true
    clean-disabled: false
    encoding: UTF-8
    baseline-on-migrate: true
    clean-on-validation-error: true
    out-of-order: true
    locations: classpath:db/migration
    sql-migration-prefix: V
    baseline-version: 1
#日志级别
logging:
  level:
    com:
      devbox:
        server:
          domain:
            repository:
              mapper: debug
