name: Deploy Kaleido
on:
  push:
    tags:
    - 'v*'
jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kaleido-server
        uses: actions/checkout@v2
      - name: kaleido Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Kaleido Build with Maven
        run: |
          mvn -B package -Pprod --file pom.xml
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KALEIDO_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
