name: Deploy Kaleido
on:
  push:
    branches: main
jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kaleido-server
        uses: actions/checkout@v2
        with:
          repository: wp2code/kaleido
          ref: main
          token: ${{ secrets.KALEIDO_TOKEN }}
          persist-credentials: true
      - name: kaleido Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: cd code repository
        shell: bash
        run: |
          cd /home/runner/work/kaleido-repo
          pwd
      - name: Kaleido Build with Maven
        run: |
          mvn -B package -Pprod --file pom.xml
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.KALEIDO_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
